# Generated by Django 5.2 on 2025-04-22 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(help_text='Classe do ícone (ex: fas fa-image)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('nivel_acesso', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nível de Acesso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribuidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='acervo/', verbose_name='Arquivo (opcional)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_estimada', models.DateField(verbose_name='Data Estimada')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('qualidade', models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EXCLUSIVO', 'Exclusivo'), ('LEGENDA', 'Lendário')], default='COMUM', max_length=10, verbose_name='Qualidade')),
                ('marcadores', models.CharField(blank=True, max_length=200, verbose_name='Marcadores (tags)')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado pela Curadoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.categoria', verbose_name='Categoria')),
                ('contribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.contribuidor', verbose_name='Contribuidor')),
                ('tipo_midia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.tipomidia', verbose_name='Tipo de Mídia')),
            ],
            options={
                'verbose_name': 'Entrada do Acervo',
                'verbose_name_plural': 'Entradas do Acervo',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data de Acesso')),
                ('ip', models.CharField(max_length=50, verbose_name='Endereço IP')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.entradaacervo', verbose_name='Entrada Acessada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Acesso',
                'verbose_name_plural': 'Registros de Acesso',
                'ordering': ['-data_acesso'],
            },
        ),
    ]
