# Generated by Django 5.1.3 on 2025-04-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaacervo',
            name='tipo_midia',
        ),
    ]
